# Generated by Django 4.0.4 on 2022-11-11 16:06

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.intelhandler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('type', models.CharField(choices=[('FEMA', "Email's origin"), ('SEMA', "Email's subject"), ('MD5H', 'File hashe MD5'), ('SHA1', 'File hashe SHA1'), ('SHA2', 'File hashe SHA256'), ('FILE', 'File name'), ('REGS', 'Registry'), ('IPAD', 'IP adresses'), ('URLS', "Full URL's"), ('DOMN', "Domain's")], default='IPAD', max_length=4, verbose_name='Тип индикатора')),
                ('link', models.TextField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('data', models.TextField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_instead_full', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='Путь к сертификату')),
                ('authenticity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Достоверность')),
                ('format', models.CharField(choices=[('STIX', 'stix'), ('MISP', 'misp'), ('FREE_TEXT', 'free_text'), ('JSON', 'json'), ('CSV', 'csv')], default='CSV', max_length=15, verbose_name='Формат')),
                ('auth_type', models.CharField(choices=[('NAU', 'Отсуствует'), ('API', 'API token'), ('BSC', 'HTTP basic')], default='NAU', max_length=3, verbose_name='Тип авторизации')),
                ('auth_login', models.CharField(blank=True, max_length=32, null=True, verbose_name='Логин для авторизации')),
                ('auth_password', models.CharField(blank=True, max_length=64, null=True, verbose_name='Пароль для авторизации')),
                ('max_rows', models.IntegerField(default=None, null=True)),
                ('raw_indicators', models.TextField(default=None, null=True)),
                ('update_time_period', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('method_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelhandler.source')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', src.intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', src.intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('comment', models.TextField(default=None, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intelhandler.activitytype')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
