before_script:
  - python3 --version  # For debugging
  - cp /home/ubuntu/.env ./threatintel/.env

#test:
#  script:
#    - python setup.py test
#    - pip install tox flake8  # you can also use tox
#    - tox -e py36,flake8

run:
  script:
    - docker-compose up --force-recreate --build -d
