version: '3.7'

services:
  docker_example_dagit:
    build:
      context: .
      dockerfile: ./threatintel/Dockerfile
    entrypoint:
      - dagit
      - -f
      - "worker/collector_consumer.py"
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
