version: "3.7"

services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: unless-stopped
    expose:
        - 5432
    env_file:
        - .env

  dagster:
    build: .
    restart: on-failure
    env_file:
        - .env
    ports:
      - "3000:3000"
    volumes:
        - .:/usr/src/app/
    depends_on:
        - db
    environment:
        - CONTAINER_TYPE=DAGSTER_CONTAINER

  enrichment:
    build: .
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - CONTAINER_TYPE=ENRICHMENT_CONTAINER

  worker:
      build: .
      volumes:
          - .:/usr/src/app/
      env_file:
          - .env
      depends_on:
          - db
      environment:
          - CONTAINER_TYPE=WORKER_CONTAINER
      ports:
          - "9000:9000"