version: "3.7"

services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: unless-stopped
    expose:
        - 5432
    env_file:
        - .env
    
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    env_file:
      - .env

  kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      env_file:
        - .env
      depends_on:
        - zookeeper
      volumes:
        - ./server.properties:/bitnami/kafka/config/server.properties

  collector:
      build: .
      volumes:
          - .:/usr/src/app/
      env_file:
          - .env
      depends_on:
          - db
          - kafka
      ports:
          - "8000:8000"

networks: 
    external:
      name: kafka_net
