psvc:
  name: Сервис Сборщика событий
  description: Сервис для сборки событий
  publishAPI: true

replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 512Mi
    cpu: 100m

databases:
  - type: POSTGRESQL
    host: 10.7.27.113
    port: 5432
    name: db

env:
  KAFKA_BOOTSTRAP_SERVER: adapter-ti-clusters-events-collector.isys-threat-intelligence-dev-links:9092
  KAFKA_GROUP_ID: main
  TOPIC_CONSUME_EVENTS: syslog
  ALLOW_ANONYMOUS_LOGIN: yes
  ALLOW_PLAINTEXT_LISTENER: yes
  SESSION_COOKIE_SECURE: False
  CSRF_ENABLED: False

links:
  - targetProtocol: "KAFKA"
      targetInformationSystemId: "events-collector"
      targetKafkaTopicId: "syslog"
      kafkaAdapterProperties:
        connectionMode: "consumer"

strategyType: Recreate
