# Generated by Django 4.0.4 on 2022-08-10 08:15

from django.db import migrations, models
import django.db.models.deletion
import intelhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0001_initial'),
    ]

    operations = [
        
    ]
