# Generated by Django 4.0.4 on 2022-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
        # migrations.CreateModel(
        #     name='Task',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created', intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
        #         ('modified', intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
        #         ('is_scheduled', models.BooleanField(default=False)),
        #         ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelhandler.source')),
        #     ],
        #     options={
        #         'get_latest_by': 'modified',
        #         'abstract': False,
        #     },
        # ),
    ]
