# Generated by Django 4.0.4 on 2022-08-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0002_alter_activity_comment'),
        ('intelhandler', '0002_task'),
    ]

    operations = [
    ]
