# Generated by Django 4.0.4 on 2022-08-12 09:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import intelhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0003_merge_0002_alter_activity_comment_0002_task'),
    ]

    operations = [

        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='push_to_detections',
            field=models.BooleanField(default=False),
        ),

    ]
