# Generated by Django 4.0.4 on 2022-08-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intelhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0007_role_alter_activity_indicator_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('method_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
