# Generated by Django 4.0.4 on 2022-09-08 10:11

from django.db import migrations, models
import intelhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelhandler', '0010_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', intelhandler.models.CreationDateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', intelhandler.models.ModificationDateTimeField(auto_now=True, verbose_name='изменено')),
                ('data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
