"""Create init tables

Revision ID: 6546eb22a4af
Revises: 
Create Date: 2022-12-08 19:54:58.094445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6546eb22a4af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('types', sa.Enum('EMAIL_FROM', 'EMAIL_SUBJECT', 'MD5_HASH', 'SHA1_HASH', 'SHA256_HASH', 'IP', 'URL', 'DOMAIN', 'FILENAME', 'REGISTRY', name='typesenum'), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sending_to_detections', sa.Boolean(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('false_detected_counter', sa.Integer(), nullable=True),
    sa.Column('positive_detected_counter', sa.Integer(), nullable=True),
    sa.Column('total_detected_counter', sa.Integer(), nullable=True),
    sa.Column('first_detected_date', sa.DateTime(), nullable=True),
    sa.Column('last_detected_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_created_at'), 'indicators', ['created_at'], unique=False)
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_is_archived'), 'indicators', ['is_archived'], unique=False)
    op.create_table('stat_checked_objects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_checked_objects_created_at'), 'stat_checked_objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_stat_checked_objects_id'), 'stat_checked_objects', ['id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indicator_id', sa.BigInteger(), nullable=True),
    sa.Column('detection_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_created_at'), 'detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_table('stat_matched_objects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('indicator_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_matched_objects_created_at'), 'stat_matched_objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_stat_matched_objects_id'), 'stat_matched_objects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stat_matched_objects_id'), table_name='stat_matched_objects')
    op.drop_index(op.f('ix_stat_matched_objects_created_at'), table_name='stat_matched_objects')
    op.drop_table('stat_matched_objects')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_created_at'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_stat_checked_objects_id'), table_name='stat_checked_objects')
    op.drop_index(op.f('ix_stat_checked_objects_created_at'), table_name='stat_checked_objects')
    op.drop_table('stat_checked_objects')
    op.drop_index(op.f('ix_indicators_is_archived'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_created_at'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
